services:
  add-file:
    entrypoint:
      - /home/python/venv/bin/python
      - /home/python/alpine-wheels/index/add-file.py
    image: ghcr.io/alpine-wheels/index-helper
    volumes:
      - ./:/home/python/alpine-wheels/index
    working_dir: /home/python/alpine-wheels/index

  publish:
    entrypoint:
      - /home/python/venv/bin/python
      - /home/python/alpine-wheels/index/publish.py
    image: ghcr.io/alpine-wheels/index-helper
    volumes:
      - ./:/home/python/alpine-wheels/index
    working_dir: /home/python/alpine-wheels/index

  shell:
    entrypoint:
      - /bin/sh
    image: ghcr.io/alpine-wheels/index-helper
    volumes:
      - ./:/home/python/alpine-wheels/index
    working_dir: /home/python/alpine-wheels/index
