version: '3.8'

services:
  publish:
    image: docker.pkg.github.com/alpine-wheels/index/publish
    build: .
    working_dir: /alpine-wheels/index
    volumes:
      - ./:/alpine-wheels/index
    entrypoint:
      - /usr/local/bin/python
    command:
      - publish.py
