version: '3.8'

services:
  publish:
    image: docker.pkg.github.com/alpine-wheels/index/alpine-wheels-index-tools
    working_dir: /workspace
    volumes:
      - ./:/workspace
    entrypoint:
      - /usr/local/bin/python
      - publish.py

  add-file:
    image: docker.pkg.github.com/alpine-wheels/index/alpine-wheels-index-tools
    working_dir: /workspace
    volumes:
      - ./:/workspace
    entrypoint:
      - /usr/local/bin/python
      - add-file.py
