services:
  add-file:
    entrypoint:
      - /usr/local/bin/python
      - add-file.py
    image: ghcr.io/alpine-wheels/index-helper
    volumes:
      - ./:/workspace
    working_dir: /workspace

  publish:
    entrypoint:
      - /usr/local/bin/python
      - publish.py
    image: ghcr.io/alpine-wheels/index-helper
    volumes:
      - ./:/workspace
    working_dir: /workspace
