name: Build the helper container image

on:
  pull_request:
    branches:
      - master
    paths:
      - .github/workflows/build-helper-image.yaml
      - Dockerfile
      - requirements.txt
  push:
    branches:
      - master
    paths:
      - .github/workflows/build-helper-image.yaml
      - Dockerfile
      - requirements.txt
  workflow_dispatch:

env:
  image_name: ghcr.io/${{ github.repository }}-helper

jobs:

  build:
    name: Build the helper container image
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build the container image
        uses: docker/build-push-action@v2
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ env.image_name }}:latest

      - name: Log in to GitHub container registry
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        uses: docker/login-action@v3
        with:
          password: ${{ github.token }}
          registry: ghcr.io
          username: ${{ github.actor }}

      - name: Push latest image to registry
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        uses: docker/build-push-action@v5
        with:
          cache-from: type=gha
          push: true
          tags: ${{ env.image_name }}:latest
