name: Build the tools container image

on:
  pull_request:
    branches:
      - master
    paths:
      - Dockerfile
      - requirements.txt
  push:
    branches:
      - master
    paths:
      - Dockerfile
      - requirements.txt

jobs:

  build:
    name: Build the tools container image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2.3.3
      - name: Build the container image
        uses: docker/build-push-action@v2
        with:
          repository: tools
      - name: Tag and push the container image
        if: github.event_name == 'push'
        uses: docker/build-push-action@v2
        with:
          repository: ${{ github.repository }}/alpine-wheels-index-tools
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ github.token }}
          tag_with_ref: true
          add_git_labels: true
