name: Build the tools container image

on:
  workflow_dispatch:

jobs:

  build:
    name: Build the tools container image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2.3.2
      - name: Log in to the GitHub registry
        run: docker login --password "${{ github.token }}" --username "${{ github.actor }}" docker.pkg.github.com
      - name: Set the image name and tag
        id: vars
        run: echo "::set-output name=image-name::docker.pkg.github.com/${{ github.repository }}/alpine-wheels-index-tools:latest"
      - name: Build the container image
        run: docker image build --file Dockerfile --tag ${{ steps.vars.outputs.image-name }} .
      - name: Push the image to the GitHub registry
        run: docker image push ${{ steps.vars.outputs.image-name }}
