name: Build the tools container image

on:
  pull_request:
    branches:
      - master
    paths:
      - .github/workflows/build-helper-image.yaml
      - Dockerfile
      - requirements.txt
  push:
    branches:
      - master
    paths:
      - .github/workflows/build-helper-image.yaml
      - Dockerfile
      - requirements.txt

jobs:

  build:
    name: Build the helper container image
    runs-on: ubuntu-latest
    steps:

      - name: Check out the repository
        uses: actions/checkout@v2.3.3

      - name: Build the container image
        uses: docker/build-push-action@v1.1.1
        with:
          repository: index-helper

      - name: Tag and push the container image
        if: github.event_name == 'push'
        uses: docker/build-push-action@v1.1.1
        with:
          repository: ${{ github.repository_owner }}/index-helper
          registry: ghcr.io
          username: ${{ secrets.ghcr_username }}
          password: ${{ secrets.ghcr_token }}
          tag_with_ref: true
          add_git_labels: true
